import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "config/material-tailwind-theme-provider";
import { ReactNode } from "react";
import ReactQueryClientProvider from "config/ReactQueryClientProvider";
import AuthProvider from "config/auth-provider";
import { createServerSupabaseClient } from "utils/supabase/server";
import Header from "components/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const pretendard = localFont({
	src: "../fonts/PretendardVariable.woff2",
	display: "swap",
	weight: "45 920",
	variable: "--font-pretendard",
});

export default async function RootLayout({ children }: { children: ReactNode }) {
	const supabase = await createServerSupabaseClient();
	const {
		data: { session },
	} = await supabase.auth.getSession();

	return (
		<html lang="ko">
			<head>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
					integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
					crossOrigin="anonymous"
					referrerPolicy="no-referrer"
				/>
			</head>
			<body className={`${pretendard.variable} font-pretendard bg-[#121B24] relative`}>
				<ReactQueryClientProvider>
					<ThemeProvider>
						<AuthProvider accessToken={session?.access_token}>
							<Header />
							{children}
						</AuthProvider>
					</ThemeProvider>
				</ReactQueryClientProvider>
			</body>
		</html>
	);
}
